# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreatHomesRealty', '0003_auto_20161120_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='mainPicture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='GreatHomesRealty.Listing'),
        ),
    ]
