# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatHomesRealty', '0004_auto_20161120_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='address',
            new_name='addressStreet',
        ),
        migrations.AddField(
            model_name='listing',
            name='addressAptNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='addressCity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='addressState',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='addressZipcode',
            field=models.IntegerField(null=True),
        ),
    ]
