# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('GreatHomesRealty', '0006_auto_20161123_1810'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('clientMgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='yearBuilt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(),
        ),
    ]
