# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatHomesRealty', '0007_auto_20161124_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='createdById',
            field=models.IntegerField(null=True),
        ),
    ]
