# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 20:17
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GreatHomesRealty', '0008_listing_createdbyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
