# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreatHomesRealty', '0010_auto_20161231_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoUrl',
        ),
    ]
