# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreatHomesRealty', '0013_listing_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='mainPicture',
        ),
    ]
