# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatHomesRealty', '0014_auto_20161231_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='lon',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
