# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatHomesRealty', '0016_auto_20170123_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='createdById',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
