# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndReg', '0003_auto_20161116_2300'),
        ('UserDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='LoginAndReg.User'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='LoginAndReg.User'),
        ),
    ]
