# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDashboard', '0006_auto_20161117_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='reciever',
        ),
        migrations.AddField(
            model_name='messages',
            name='subject',
            field=models.TextField(null=True),
        ),
    ]
