# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndReg', '0002_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileInformation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
