# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginAndReg', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('user_level', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=250)),
                ('birthday', models.DateField(null=True)),
                ('profileInformation', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            managers=[
                ('registerMgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
