# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndReg', '0006_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
