# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndReg', '0008_auto_20161124_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
