# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndReg', '0009_remove_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
