# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndReg', '0010_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
